import { internalMutation } from "./_generated/server";
import { createCanonicalExercise, assignExerciseToTrainerHelper } from "./lib/sharedHelpers";

export const seedRemainingNotionExercises = internalMutation({
  args: {},
  handler: async (ctx) => {
    // Get or create active trainer
    const trainers = await ctx.db.query("trainers").collect();
    let activeTrainer = trainers.find((t) => t.isActive);
    
    if (!activeTrainer) {
      const trainerId = await ctx.db.insert("trainers", {
        firstName: "Jasmine",
        lastName: "Trainer",
        fullName: "Jasmine Trainer",
        email: "jasmine@bodybridge.fitness",
        updatedAt: Date.now(),
        isActive: true,
      });
      activeTrainer = {
        _id: trainerId,
        firstName: "Jasmine",
        lastName: "Trainer",
        fullName: "Jasmine Trainer",
        email: "jasmine@bodybridge.fitness",
        updatedAt: Date.now(),
        isActive: true,
      };
    }

    const exercises = [
      {
        notionPageId: "31597d6b-662f-80a1-84fe-db934810a1f4",
        title: "Finger Extension",
        videoUrl: "https://youtube.com/shorts/CEAdgGuZYi0?feature=share",
        bodyRegion: "Hand",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Finger extension is the motion of straightening your fingers and opening the hand. This drill improves hand control and tendon glide.",
        instructions: "Sit with shoulders relaxed. Rest forearm on table. Start with hand relaxed. Slowly straighten fingers into flat palm. Pause, then return to relaxed position.",
      },
      {
        notionPageId: "31597d6b-662f-802c-8a87-dfb7c3b46647",
        title: "Finger Flexion",
        videoUrl: "https://youtube.com/shorts/t4e7SYz2oVs?feature=share",
        bodyRegion: "Hand",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Finger flexion is the motion of bending your fingers to grip (closing the hand). This drill supports daily tasks like holding objects.",
        instructions: "Sit with shoulders relaxed. Rest forearm on table. Start with fingers straight. Slowly bend fingers into gentle fist. Pause, then open hand with control.",
      },
      {
        notionPageId: "31597d6b-662f-80c2-9301-ea94431456f9",
        title: "Forearm Pronation",
        videoUrl: "https://youtube.com/shorts/lWtiDSzAjY4?feature=share",
        bodyRegion: "Forearm",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Forearm pronation is the motion of rotating your forearm so your palm faces down. Used in typing, pushing doors, and using tools.",
        instructions: "Sit with shoulders relaxed. Bend elbow 90 degrees, close to side. Start palm up or neutral. Slowly rotate forearm so palm turns downward. Pause, then return.",
      },
      {
        notionPageId: "31597d6b-662f-80d0-8319-ef516de50dc4",
        title: "Forearm Supnation",
        videoUrl: "https://youtu.be/yu6QVFdfJ3k",
        bodyRegion: "Forearm",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Forearm supination is rotating your forearm so your palm faces up. Supports turning keys, opening doors, carrying trays.",
        instructions: "Sit with shoulders relaxed. Bend elbow 90 degrees, close to side. Start palm down or neutral. Slowly rotate forearm so palm turns upward. Pause, then return.",
      },
      {
        notionPageId: "2fb97d6b-662f-80d2-9ad1-d66799ea811f",
        title: "Hip Extension",
        videoUrl: "https://youtube.com/shorts/KzgeJOKvIFw?feature=share",
        bodyRegion: "Pelvis",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Hip extension builds strength through the posterior chain. Crucial for correcting anterior pelvic tilt and preventing low back pain.",
        instructions: "Lie on back, knees bent, feet flat. Press through heels, lift hips toward ceiling, squeeze glutes. Keep ribs down. Lower with control.",
      },
      {
        notionPageId: "2fb97d6b-662f-8029-b5e6-f1e9b57459a7",
        title: "Hip Flexion",
        videoUrl: "https://youtube.com/shorts/p1OHft9eHWo?feature=share",
        bodyRegion: "Pelvis",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Hip flexion supports walking, squatting, and core control. Teaches mindful activation without compensating from the lower back.",
        instructions: "Lie on back, knees bent. Lift one knee toward chest, keeping pelvis stable. Do not arch back or twist hips. Lower slowly, repeat other side.",
      },
      {
        notionPageId: "2fa97d6b-662f-80b4-8e76-e2f464b4d9eb",
        title: "Mandible Depression",
        videoUrl: "https://youtube.com/shorts/AblgH8J3mqE?feature=share",
        bodyRegion: "Mandible",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Mandible depression lowers the jaw to help relieve tension and improve TMJ mobility. Focus on smooth motion downward.",
        instructions: "Sit or stand upright. Slowly open mouth by lowering jaw in controlled motion. Open halfway to full open, stopping before pain. Close gently.",
      },
      {
        notionPageId: "2fa97d6b-662f-8044-a06a-c8d1e65deff6",
        title: "Mandible Elevation",
        videoUrl: "https://youtube.com/shorts/Z80a8pkxzFI?feature=share",
        bodyRegion: "Mandible",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Mandible elevation is controlled jaw closing. Emphasize smooth movement using jaw muscles, not the neck. Helps bite alignment.",
        instructions: "Sit upright, mouth gently open. Slowly close jaw by bringing lower jaw upward until teeth are gently together. Keep jaw centered.",
      },
      {
        notionPageId: "2fa97d6b-662f-8050-b5c9-ea96e9f9ff13",
        title: "Mandible Lateral Deviation",
        videoUrl: "https://youtube.com/shorts/Dkb0slx8Zjs?feature=share",
        bodyRegion: "Mandible",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Mandible lateral deviation moves your jaw side to side. Improves jaw mobility and balance between sides for TMJ health.",
        instructions: "Sit upright. Slowly move lower jaw to right, shifting bottom teeth past top teeth. Return to center. Repeat to left. Keep movement horizontal.",
      },
      {
        notionPageId: "2fa97d6b-662f-8090-ad20-dd36c0a9facc",
        title: "Mandible Protraction",
        videoUrl: "https://youtube.com/shorts/qfJX_H9Ka_w?feature=share",
        bodyRegion: "Mandible",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Mandible protraction slides the lower jaw forward. Improves jaw control and mobility, helpful for TMJ health.",
        instructions: "Sit upright. Slowly slide lower jaw forward so bottom teeth move in front of top teeth. Keep motion horizontal. Return gently.",
      },
      {
        notionPageId: "2fa97d6b-662f-80b1-8e2e-f0b98f9799df",
        title: "Mandible Retraction",
        videoUrl: "https://youtube.com/shorts/2K7FaNHGAoc?feature=share",
        bodyRegion: "Mandible",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Mandible retraction pulls the jaw backward. Great for posture correction and jaw alignment.",
        instructions: "Sit upright. Gently pull lower jaw back, aligning bottom teeth beneath top teeth. Do not tilt head. Pause, then return forward.",
      },
      {
        notionPageId: "2f397d6b-662f-8061-a349-d942eb75fef3",
        title: "Neck Circles",
        videoUrl: "https://youtube.com/shorts/upJudRwD9hg?feature=share",
        bodyRegion: "Neck",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Neck circles gently mobilize the neck and improve flexibility in all directions. Great for warm-ups or decompressing.",
        instructions: "Sit tall. Lower chin to chest, circle head to right, tilt back, roll to left shoulder, return to chin. Reverse direction. 3-5 circles each way.",
      },
      {
        notionPageId: "2f397d6b-662f-8095-b47b-ffe40f45b31e",
        title: "Neck Flexion & Extension",
        videoUrl: "https://youtube.com/shorts/wi17FcnPzCA?feature=share",
        bodyRegion: "Neck",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Neck flexion and extension improve mobility, posture, and relieve tension through controlled forward and backward motion.",
        instructions: "Sit tall. Slowly lower chin toward chest, feel gentle stretch in back of neck. Pause, then lift chin toward ceiling without arching back.",
      },
      {
        notionPageId: "2f397d6b-662f-8099-91b0-ffd29a9d8e3a",
        title: "Neck Lateral Flexion",
        videoUrl: "https://youtube.com/shorts/MAacLT48Mrk?feature=share",
        bodyRegion: "Neck",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Neck lateral flexion gently stretches and strengthens muscles on the sides of your neck. Relieves tension.",
        instructions: "Sit tall. Slowly tilt right ear toward right shoulder without lifting shoulder. Pause, return to center. Repeat left side.",
      },
      {
        notionPageId: "2f397d6b-662f-809e-8543-e42eb52d7c97",
        title: "Neck Rotation",
        videoUrl: "https://youtube.com/shorts/E0wR5ZylNUo?feature=share",
        bodyRegion: "Neck",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Neck rotation improves range of motion, releases neck stiffness, and promotes better alignment.",
        instructions: "Sit tall. Slowly turn head to right, looking over shoulder. Keep chin level. Pause, return to center. Repeat to left.",
      },
      {
        notionPageId: "2fb97d6b-662f-8092-a95a-d2211af7b214",
        title: "Rib Elevation & Depression",
        videoUrl: "https://youtube.com/shorts/ychuyxE7a2U?feature=share",
        bodyRegion: "Spine & Thorax",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Rib elevation and depression retrain proper breathing mechanics and improve thoracic mobility.",
        instructions: "Sit or lie with neutral spine. Inhale deeply, expanding ribs outward/upward. Exhale slowly, drawing ribs downward/inward.",
      },
      {
        notionPageId: "2f897d6b-662f-8074-b295-cc65ea6d2cc4",
        title: "Scapula Depression",
        videoUrl: "https://youtube.com/shorts/KE64CteMzlc?feature=share",
        bodyRegion: "Scapula",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Scapula depression activates muscles that pull shoulder blades down. Key for improving posture.",
        instructions: "Sit or stand tall. Slowly draw shoulder blades downward toward back pockets. Lengthen neck. Hold 1-2 seconds, release.",
      },
      {
        notionPageId: "2f897d6b-662f-80da-87d6-c29fd6eef242",
        title: "Scapula Downward Rotation",
        videoUrl: "https://youtube.com/shorts/uzJX9QXmlDQ?feature=share",
        bodyRegion: "Scapula",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Scapula downward rotation draws shoulder blades downward and inward. Strengthens upper back stabilizers.",
        instructions: "Stand tall, arms overhead in Y position. Pull elbows down and back, squeezing shoulder blades down and in. Return to start.",
      },
      {
        notionPageId: "2f897d6b-662f-80b6-8703-c1b309099428",
        title: "Scapula Elevation",
        videoUrl: "https://youtube.com/shorts/YWgjy6P2_u4?feature=share",
        bodyRegion: "Scapula",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Scapula elevation lifts shoulder blades upward in controlled motion. Builds awareness of upper trap mechanics.",
        instructions: "Stand tall. Slowly lift both shoulders straight up toward ears. Avoid rolling forward/back. Pause 1-2 seconds, lower slowly.",
      },
      {
        notionPageId: "2f897d6b-662f-8085-9c29-cd3fc1e72e8b",
        title: "Scapula Protraction",
        videoUrl: "https://youtube.com/shorts/fDoS1MRW5Ug?feature=share",
        bodyRegion: "Scapula",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Scapula protraction glides shoulder blades forward. Foundation for shoulder stability and posture correction.",
        instructions: "Stand with arms extended forward at chest height. Push arms forward by gliding shoulder blades away from spine. Return.",
      },
      {
        notionPageId: "2f897d6b-662f-8049-a84e-e09c8d9c00e2",
        title: "Scapula Retraction",
        videoUrl: "https://youtube.com/shorts/5dnrp4W-6sI?feature=share",
        bodyRegion: "Scapula",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Scapula retraction pulls shoulder blades together. Strengthens mid-back muscles and improves posture.",
        instructions: "Sit or stand tall with arms extended forward. Pull shoulder blades back and together, squeezing mid-back. Hold briefly, release.",
      },
      {
        notionPageId: "2f897d6b-662f-802c-bd6f-8e7975966156",
        title: "Scapula Upward Rotation",
        videoUrl: "https://youtube.com/shorts/5m9i4xkJ3QE?feature=share",
        bodyRegion: "Scapula",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Scapula upward rotation elevates shoulder blades while rotating them. Essential for overhead movement.",
        instructions: "Start arms down. Raise arms overhead in Y position. Feel shoulder blades rotate upward. Lower with control.",
      },
      {
        notionPageId: "2f897d6b-662f-8097-8268-5052283c233f",
        title: "Shoulder Abduction",
        videoUrl: "https://youtube.com/shorts/6x0Wb8UcNBI?feature=share",
        bodyRegion: "Shoulder",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Shoulder abduction lifts arm away from body sideways. Builds stability and awareness.",
        instructions: "Stand tall. Slowly lift one arm out to side until it reaches shoulder height. Keep palm down. Pause, lower with control.",
      },
      {
        notionPageId: "2f897d6b-662f-80a8-9067-2df9155269bf",
        title: "Shoulder Adduction",
        videoUrl: "https://youtube.com/shorts/eJN9j2jFjEQ?feature=share",
        bodyRegion: "Shoulder",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Shoulder adduction brings arm toward body midline. Complements abduction for full shoulder control.",
        instructions: "Start with arm lifted out to side. Slowly lower arm down to your side. Control the motion throughout.",
      },
      {
        notionPageId: "2f897d6b-662f-8054-9b2d-a9791ed6d3af",
        title: "Shoulder Extension",
        videoUrl: "https://youtube.com/shorts/GNV8sQ2Nc98?feature=share",
        bodyRegion: "Shoulder",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Shoulder extension moves arm backward behind body. Important for reaching and lifting.",
        instructions: "Stand tall. Slowly move one arm backward behind you. Keep arm straight. Pause, return to starting position.",
      },
      {
        notionPageId: "2f897d6b-662f-8037-b5af-c64e44234a88",
        title: "Shoulder External Rotation",
        videoUrl: "https://youtube.com/shorts/OYh9RVYpMfA?feature=share",
        bodyRegion: "Shoulder",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Shoulder external rotation rotates arm outward. Critical for shoulder health and rotator cuff function.",
        instructions: "Stand with elbow bent 90 degrees at side. Slowly rotate forearm outward, moving hand away from body. Return with control.",
      },
      {
        notionPageId: "2f897d6b-662f-8038-9773-562cf32712c6",
        title: "Shoulder Flexion",
        videoUrl: "https://youtube.com/shorts/5uG1-gwnhqo?feature=share",
        bodyRegion: "Shoulder",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Shoulder flexion lifts arm forward and overhead. Essential for reaching and daily activities.",
        instructions: "Stand tall. Slowly lift one arm forward and upward until it reaches overhead. Keep arm straight. Pause, lower with control.",
      },
      {
        notionPageId: "2f897d6b-662f-806d-a1fe-0272a5c47b70",
        title: "Shoulder Horizontal Abduction",
        videoUrl: "https://youtube.com/shorts/EdM0WpXIqCY?feature=share",
        bodyRegion: "Shoulder",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Shoulder horizontal abduction moves arm across body away from midline. Improves posterior shoulder mobility.",
        instructions: "Start arm extended forward at shoulder height. Slowly move arm outward to side, across body. Keep arm straight. Return.",
      },
      {
        notionPageId: "2f897d6b-662f-8065-bc9e-4b3b7db90e28",
        title: "Shoulder Horizontal Adduction",
        videoUrl: "https://youtube.com/shorts/uMvDN8zV5KE?feature=share",
        bodyRegion: "Shoulder",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Shoulder horizontal adduction moves arm across body toward midline. Strengthens chest and anterior shoulder.",
        instructions: "Start arm extended out to side at shoulder height. Slowly bring arm across body toward opposite shoulder. Keep arm straight. Return.",
      },
      {
        notionPageId: "2f897d6b-662f-8070-8b10-30e6c2a723c3",
        title: "Shoulder Internal Rotation",
        videoUrl: "https://youtube.com/shorts/SnJC2HZ3uL0?feature=share",
        bodyRegion: "Shoulder",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Shoulder internal rotation rotates arm inward. Important for shoulder stability and function.",
        instructions: "Stand with elbow bent 90 degrees at side, hand out. Slowly rotate forearm inward across body. Return with control.",
      },
      {
        notionPageId: "2fb97d6b-662f-8059-af72-d16e7df87db7",
        title: "SMR: Adductors",
        videoUrl: "https://youtube.com/shorts/5e9T_0yB4iM?feature=share",
        bodyRegion: "Pelvis",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "SMR for adductors releases inner thigh tension using foam rolling. Improves hip mobility.",
        instructions: "Lie face down with foam roller under inner thigh. Roll from groin to knee, pausing on tender spots. Switch legs.",
      },
      {
        notionPageId: "2fb97d6b-662f-8063-98b8-e2e2f707c04b",
        title: "SMR: Calves (Gastrocnemius/Soleus)",
        videoUrl: "https://youtube.com/shorts/a6G8l9A6xYc?feature=share",
        bodyRegion: "Ankle",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "SMR for calves releases tension in gastrocnemius and soleus muscles. Improves ankle mobility.",
        instructions: "Sit with foam roller under calf. Roll from ankle to knee, pausing on tight spots. Cross one leg for more pressure. Switch sides.",
      },
      {
        notionPageId: "2fb97d6b-662f-807d-88f5-8df22be7f7e2",
        title: "SMR: Hamstrings",
        videoUrl: "https://youtube.com/shorts/a6G8l9A6xYc?feature=share",
        bodyRegion: "Pelvis",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "SMR for hamstrings releases posterior thigh tension. Improves hip mobility and reduces low back strain.",
        instructions: "Sit with foam roller under hamstrings. Roll from knee to glutes, pausing on tender spots. Cross one leg for more pressure.",
      },
      {
        notionPageId: "2fb97d6b-662f-8068-9d77-51e0dd91c934",
        title: "SMR: Peroneals",
        videoUrl: "https://youtube.com/shorts/a6G8l9A6xYc?feature=share",
        bodyRegion: "Ankle",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "SMR for peroneals releases outer lower leg tension. Improves ankle stability and mobility.",
        instructions: "Lie on side with foam roller under outer lower leg. Roll from knee to ankle, pausing on tight spots. Switch sides.",
      },
      {
        notionPageId: "2fb97d6b-662f-807e-8336-5c51a72b77b6",
        title: "SMR: Quadriceps",
        videoUrl: "https://youtube.com/shorts/a6G8l9A6xYc?feature=share",
        bodyRegion: "Pelvis",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "SMR for quadriceps releases front thigh tension. Improves knee mobility and hip function.",
        instructions: "Lie face down with foam roller under quads. Roll from hip to knee, pausing on tender spots. Shift to target different areas.",
      },
      {
        notionPageId: "2f397d6b-662f-8065-97ba-2432675400ee",
        title: "Thoracic Extension",
        videoUrl: "https://youtube.com/shorts/rB3vIToK9V0?feature=share",
        bodyRegion: "Spine & Thorax",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Thoracic extension improves upper back mobility and posture. Counters forward head and rounded shoulders.",
        instructions: "Sit on chair, hands behind head. Gently arch upper back over chair back. Feel gentle stretch in chest. Return to neutral.",
      },
      {
        notionPageId: "2f397d6b-662f-8041-8242-2338b17c1943",
        title: "Thoracic Flexion",
        videoUrl: "https://youtube.com/shorts/jz_l9dRP4gI?feature=share",
        bodyRegion: "Spine & Thorax",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Thoracic flexion rounds the upper back. Improves spinal mobility and core engagement.",
        instructions: "Sit tall. Slowly round upper back forward, bringing chest toward thighs. Tuck chin slightly. Return to neutral with control.",
      },
      {
        notionPageId: "2f397d6b-662f-8057-bc17-c3cd6958e6b4",
        title: "Thoracic Lateral Flexion",
        videoUrl: "https://youtube.com/shorts/CE9zTkq-2_Q?feature=share",
        bodyRegion: "Spine & Thorax",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Thoracic lateral flexion side-bends the upper back. Improves lateral spinal mobility.",
        instructions: "Sit tall. Reach one arm overhead and lean to opposite side. Feel stretch along side of torso. Return, repeat other side.",
      },
      {
        notionPageId: "2f397d6b-662f-8079-8e6e-586b89e7b943",
        title: "Thoracic Rotation",
        videoUrl: "https://youtube.com/shorts/3cDqhXukq0I?feature=share",
        bodyRegion: "Spine & Thorax",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Thoracic rotation rotates the upper back. Improves spinal mobility and reduces stiffness.",
        instructions: "Sit tall, hands crossed over chest. Slowly rotate upper body to one side, keeping hips still. Pause, return. Repeat other side.",
      },
      {
        notionPageId: "31597d6b-662f-8060-939d-8ec565037576",
        title: "Thumb Extension",
        videoUrl: "https://youtube.com/shorts/3W7pKfVgR9E?feature=share",
        bodyRegion: "Hand",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Thumb extension moves thumb away from hand. Improves thumb mobility and grip function.",
        instructions: "Sit with hand relaxed. Slowly move thumb away from palm, opening the web space. Pause, return to starting position.",
      },
      {
        notionPageId: "31597d6b-662f-8065-9394-f50c319e1c84",
        title: "Thumb Flexion",
        videoUrl: "https://youtube.com/shorts/JgHfuNz5eY8?feature=share",
        bodyRegion: "Hand",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Thumb flexion moves thumb across palm. Improves thumb mobility and grip strength.",
        instructions: "Sit with hand relaxed. Slowly move thumb across palm toward little finger. Pause, return to starting position.",
      },
      {
        notionPageId: "31597d6b-662f-8079-9215-5c5e2fc7202c",
        title: "Thumb Opposition",
        videoUrl: "https://youtube.com/shorts/XbvnCZuHDzk?feature=share",
        bodyRegion: "Hand",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Thumb opposition touches thumb to fingertips. Essential for fine motor skills and grip.",
        instructions: "Sit with hand relaxed. Touch thumb tip to each fingertip in sequence. Return between each. Repeat in reverse.",
      },
      {
        notionPageId: "31597d6b-662f-802f-86c7-a7f76c7277e8",
        title: "Wrist Abduction",
        videoUrl: "https://youtube.com/shorts/8RvQ6VH-Tcs?feature=share",
        bodyRegion: "Hand",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Wrist abduction moves hand toward thumb side. Improves wrist mobility and reduces strain.",
        instructions: "Sit with forearm supported, thumb up. Slowly move hand toward thumb side, keeping forearm still. Pause, return.",
      },
      {
        notionPageId: "31597d6b-662f-8033-86c0-bf0366295109",
        title: "Wrist Adduction",
        videoUrl: "https://youtube.com/shorts/rqB6I6B5bvw?feature=share",
        bodyRegion: "Hand",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Wrist adduction moves hand toward little finger side. Improves wrist mobility and balance.",
        instructions: "Sit with forearm supported, thumb up. Slowly move hand toward little finger side, keeping forearm still. Pause, return.",
      },
      {
        notionPageId: "31597d6b-662f-8044-8609-d63613fb6fae",
        title: "Wrist Extension",
        videoUrl: "https://youtube.com/shorts/XH0-gd_4_E0?feature=share",
        bodyRegion: "Hand",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Wrist extension bends hand back toward forearm. Improves wrist mobility and reduces tightness.",
        instructions: "Sit with forearm supported, palm down. Slowly bend hand back, lifting palm toward ceiling. Pause, return to neutral.",
      },
      {
        notionPageId: "31597d6b-662f-8048-8615-f1c477d05a64",
        title: "Wrist Flexion",
        videoUrl: "https://youtube.com/shorts/6m_YFz9h1cw?feature=share",
        bodyRegion: "Hand",
        movementGoal: "Mobility",
        level: "Beginner",
        equipment: "Bodyweight",
        videoDescription: "Wrist flexion bends hand toward forearm palm side. Improves wrist mobility and grip function.",
        instructions: "Sit with forearm supported, palm up. Slowly bend hand forward, lowering palm toward floor. Pause, return to neutral.",
      },
    ];

    const results = { created: 0, updated: 0, errors: [] as string[] };

    for (const ex of exercises) {
      try {
        const exerciseId = await createCanonicalExercise(ctx, {
          name: ex.title,
          sourceSystem: "notion",
          sourceId: `notion:${ex.notionPageId}`,
          category: ex.movementGoal === "Mobility" ? "Mobility" : "Strength",
          bodyRegion: ex.bodyRegion || "Other",
          primaryMuscles: [],
          secondaryMuscles: [],
          equipment: [ex.equipment || "Bodyweight"],
          difficulty: (ex.level === "Intermediate" ? "Intermediate" : ex.level === "Advanced" ? "Advanced" : "Beginner") as "Beginner" | "Intermediate" | "Advanced",
          overview: ex.videoDescription || "",
          instructions: ex.instructions || "",
          lifecycle: "ready",
        });

        const assignment = await assignExerciseToTrainerHelper(ctx, {
          trainerId: activeTrainer._id as any,
          exerciseId,
          videoUrl: ex.videoUrl,
          sourceSystem: "notion",
          sourceId: ex.notionPageId,
        });

        if (assignment.status === "created") results.created++;
        else results.updated++;
      } catch (e) {
        results.errors.push(`${ex.title}: ${String(e)}`);
      }
    }

    return results;
  },
});