#!/usr/bin/env node
/**
 * Generate deterministic canonicalization plan from duplicate analysis.
 * 
 * This script reads canonicalization/duplicates.json and generates
 * a TypeScript plan file with stable group IDs and hashes.
 * 
 * Output: convex/migrations/canonicalizationPlan.ts
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const DUPLICATES_FILE = path.join(__dirname, 'duplicates.json');
const OUTPUT_FILE = path.join(__dirname, '../../convex/migrations/canonicalizationPlan.ts');

/**
 * Generate SHA-256 hash
 */
function hashString(content) {
  return crypto
    .createHash('sha256')
    .update(content)
    .digest('hex');
}

/**
 * Generate stable group ID from canonical ID and duplicate IDs
 */
function generateGroupId(canonicalId, duplicateIds, planVersion) {
  const sortedDuplicateIds = [...duplicateIds].sort();
  const content = `${canonicalId}|${sortedDuplicateIds.join(',')}|${planVersion}`;
  return hashString(content);
}

/**
 * Normalize object for deterministic hashing
 */
function normalizeObject(obj) {
  if (obj === null || obj === undefined) {
    return null;
  }
  
  if (typeof obj !== 'object') {
    return obj;
  }
  
  if (Array.isArray(obj)) {
    const seen = new Set();
    const sorted = [];
    
    for (const item of obj) {
      const normalized = normalizeObject(item);
      const key = JSON.stringify(normalized);
      if (!seen.has(key)) {
        seen.add(key);
        sorted.push(normalized);
      }
    }
    
    // Sort primitives
    return sorted.sort((a, b) => {
      if (typeof a === 'string' && typeof b === 'string') {
        return a.localeCompare(b);
      }
      if (typeof a === 'number' && typeof b === 'number') {
        return a - b;
      }
      return 0;
    });
  }
  
  // Sort object keys
  const sorted = {};
  const keys = Object.keys(obj).sort();
  for (const key of keys) {
    sorted[key] = normalizeObject(obj[key]);
  }
  
  return sorted;
}

/**
 * Generate hash of groups array
 */
function generateGroupsHash(groups) {
  const normalized = groups.map(g => normalizeObject({
    groupId: g.groupId,
    canonicalExerciseId: g.canonicalExerciseId,
    duplicateExerciseIds: g.duplicateExerciseIds,
    exerciseName: g.exerciseName,
    canonicalPatch: g.canonicalPatch,
    preserveSourceId: g.preserveSourceId
  }));
  
  return hashString(JSON.stringify(normalized));
}

/**
 * Read duplicates analysis
 */
function readDuplicates() {
  if (!fs.existsSync(DUPLICATES_FILE)) {
    console.error(`Duplicates file not found: ${DUPLICATES_FILE}`);
    console.error('Please run analysis first: node analyzeExport.cjs');
    process.exit(1);
  }
  
  const content = fs.readFileSync(DUPLICATES_FILE, 'utf8');
  return JSON.parse(content);
}

/**
 * Generate TypeScript plan file content
 */
function generatePlanContent(planData) {
  const { generatedAt, sourceSnapshotHash, groups, summary } = planData;
  const planVersion = '1.0.0';
  
  // Generate stable group IDs
  const groupsWithIds = groups.map(group => ({
    ...group,
    groupId: generateGroupId(group.canonicalExerciseId, group.duplicateExerciseIds, planVersion)
  }));
  
  // Sort groups by groupId for determinism
  groupsWithIds.sort((a, b) => a.groupId.localeCompare(b.groupId));
  
  // Generate groups hash
  const groupsHash = generateGroupsHash(groupsWithIds);
  
  // Validate structure
  validatePlan(groupsWithIds, summary);
  
  // Generate TypeScript code
  const groupsCode = groupsWithIds.map(g => {
    const patchCode = g.canonicalPatch 
      ? `    canonicalPatch: ${JSON.stringify(g.canonicalPatch, null, 6)},`
      : '';
    
    const preserveCode = g.preserveSourceId !== undefined && g.preserveSourceId !== null
      ? `    preserveSourceId: '${g.preserveSourceId}',`
      : '';
    
    return `  {
    groupId: '${g.groupId}',
    canonicalExerciseId: '${g.canonicalExerciseId}',
    duplicateExerciseIds: ${JSON.stringify(g.duplicateExerciseIds)},
    exerciseName: '${g.exerciseName.replace(/'/g, "\\'")}',
${patchCode}
${preserveCode}
  }`;
  }).join(',\n');
  
  return `/**
 * Canonicalization Plan for Body Bridge Exercise Cleanup
 * 
 * This file is generated by scripts/canonicalization/generatePlan.cjs
 * from a production export snapshot.
 * 
 * DO NOT EDIT MANUALLY - regenerate from export data.
 * 
 * Generated: ${new Date(generatedAt).toISOString()}
 * Source Snapshot Hash: ${sourceSnapshotHash}
 * Groups Hash: ${groupsHash}
 * Plan Version: ${planVersion}
 */

/**
 * CanonicalPatch: Optional patches to apply to canonical exercise
 * 
 * Each patch field contains:
 * - from: The current value on the canonical exercise
 * - to: The value to set (from a duplicate)
 * 
 * Mergeable fields:
 * - overview, benefits, primaryMuscles, secondaryMuscles
 * - equipment, tags, instructions, sets, reps, tempo, rest, weight
 */
export interface CanonicalPatch {
  [key: string]: {
    from: any;
    to: any;
  };
}

export const planVersion = '${planVersion}';
export const generatedAt = ${generatedAt};
export const groupsHash = '${groupsHash}';
export const sourceSnapshotHash = '${sourceSnapshotHash}';

/**
 * Groups of duplicate exercises to canonicalize.
 * 
 * Each group contains:
 * - groupId: Stable hash of canonicalId + duplicateIds + planVersion
 * - canonicalExerciseId: The exercise to preserve
 * - duplicateExerciseIds: Exercises to delete (sorted)
 * - exerciseName: Human-readable name for logging
 * - canonicalPatch: Optional patches to apply to canonical
 * - preserveSourceId: Optional sourceId to preserve on canonical
 */
export const groups: Array<{
  groupId: string;
  canonicalExerciseId: string;
  duplicateExerciseIds: string[];
  exerciseName: string;
  canonicalPatch?: CanonicalPatch;
  preserveSourceId?: string | null;
}> = [
${groupsCode}
];

/**
 * Placeholder for approved preflight hash.
 * Set this after running preflight and approving the plan.
 */
export const approvedPreflightHash = '';

/**
 * Plan Statistics (for validation)
 */
export const planStats = {
  totalGroups: ${summary.duplicateGroups},
  totalDuplicatesToRemove: ${summary.totalDuplicatesToRemove},
  expectedAfterCanonicalization: ${summary.expectedAfterCanonicalization},
  currentExerciseCount: ${summary.totalExercises}
};
`;
}

/**
 * Validate plan structure
 */
function validatePlan(groups, summary) {
  const canonicalIds = new Set();
  const allDuplicateIds = new Set();
  
  for (const group of groups) {
    // Check for duplicate canonical IDs
    if (canonicalIds.has(group.canonicalExerciseId)) {
      throw new Error(`Duplicate canonical exercise ID: ${group.canonicalExerciseId}`);
    }
    canonicalIds.add(group.canonicalExerciseId);
    
    // Check for overlap between canonical and duplicates
    if (group.duplicateExerciseIds.includes(group.canonicalExerciseId)) {
      throw new Error(`Group ${group.groupId} has canonical ID in duplicates: ${group.canonicalExerciseId}`);
    }
    
    // Check for duplicate duplicate IDs
    for (const dupId of group.duplicateExerciseIds) {
      if (canonicalIds.has(dupId)) {
        throw new Error(`Duplicate ID ${dupId} is canonical in another group`);
      }
      if (allDuplicateIds.has(dupId)) {
        throw new Error(`Duplicate ID ${dupId} appears in multiple groups`);
      }
      allDuplicateIds.add(dupId);
    }
    
    // Verify duplicates are sorted
    for (let i = 1; i < group.duplicateExerciseIds.length; i++) {
      if (group.duplicateExerciseIds[i] < group.duplicateExerciseIds[i - 1]) {
        throw new Error(`Duplicate IDs not sorted in group ${group.groupId}`);
      }
    }
  }
  
  // Verify counts match
  const totalDuplicates = groups.reduce((sum, g) => sum + g.duplicateExerciseIds.length, 0);
  if (totalDuplicates !== summary.totalDuplicatesToRemove) {
    throw new Error(`Duplicate count mismatch: ${totalDuplicates} != ${summary.totalDuplicatesToRemove}`);
  }
  
  console.log('✓ Plan validation passed');
}

/**
 * Main execution
 */
function main() {
  console.log('=== Canonicalization Plan Generation ===\n');
  
  // Read duplicates analysis
  const duplicatesData = readDuplicates();
  console.log(`Loaded duplicate analysis from ${DUPLICATES_FILE}\n`);
  
  console.log('Summary:');
  console.log(`  Total exercises: ${duplicatesData.summary.totalExercises}`);
  console.log(`  Duplicate groups: ${duplicatesData.summary.duplicateGroups}`);
  console.log(`  Duplicates to remove: ${duplicatesData.summary.totalDuplicatesToRemove}`);
  console.log(`  Expected after: ${duplicatesData.summary.expectedAfterCanonicalization}\n`);
  
  // Generate plan content
  const planContent = generatePlanContent(duplicatesData);
  
  // Write output
  fs.writeFileSync(OUTPUT_FILE, planContent);
  
  console.log(`✓ Generated plan: ${OUTPUT_FILE}`);
  console.log(`✓ Groups: ${duplicatesData.groups.length}`);
  console.log(`✓ Groups hash: ${duplicatesData.groupsHash}`);
}

// Run
main();