import { mutation, query, internalMutation, internalQuery, QueryCtx, MutationCtx } from '../_generated/server';
import { v } from 'convex/values';
import type { Doc, Id } from '../_generated/dataModel';
import {
  assertAdminSecret,
  requireAdminSecret,
  hashString,
  hashObject,
  generateGroupId,
  generateLockToken,
  isValidLockToken,
  estimateBatchSize,
  logMigration,
} from './migrationHelpers';

// ============== Type Definitions ==============

/**
 * Status of the migration process.
 */
type MigrationStatus =
  | 'pending'
  | 'running'
  | 'paused'
  | 'completed'
  | 'blocked'
  | 'failed';

/**
 * Canonical patch structure for merging duplicate exercise data.
 * Only fields that differ between duplicates and canonical are included.
 * Trainer-specific fields are excluded (canonical only).
 */
export interface CanonicalPatch {
  overview?: { from: string | null; to: string };
  benefits?: { from: string[] | null; to: string[] };
  primaryMuscles?: { from: string[] | null; to: string[] };
  secondaryMuscles?: { from: string[] | null; to: string[] };
  equipment?: { from: string[] | null; to: string[] };
  tags?: { from: string[] | null; to: string[] };
  instructions?: { from: string[] | null; to: string[] };
  sets?: { from: string | null; to: string };
  reps?: { from: string | null; to: string };
  tempo?: { from: string | null; to: string };
  rest?: { from: string | null; to: string };
  weight?: { from: string | null; to: string };
}

/**
 * Group in the canonicalization plan.
 */
export interface CanonicalizationGroup {
  groupId: string;
  canonicalExerciseId: string;
  duplicateExerciseIds: string[];
  exerciseName: string;
  canonicalPatch?: CanonicalPatch;
  preserveSourceId?: string | null;
  expectedConflicts?: string[]; // trainerIds where conflicts are expected
}

/**
 * Batch in the execution manifest.
 */
export interface CanonicalizationBatch {
  batchId: string;
  groupIds: string[];
  estimatedReads: number;
  estimatedWrites: number;
}

/**
 * Complete batch manifest for bounded execution.
 */
export interface CanonicalizationBatchManifest {
  manifestVersion: string;
  manifestHash: string;
  planHash: string;
  preflightHash: string;
  generatedAt: number;
  totalBatches: number;
  batches: CanonicalizationBatch[];
}

/**
 * Plan loaded from canonicalizationPlan.ts
 */
interface CanonicalizationPlan {
  planVersion: string;
  generatedAt: number;
  groupsHash: string;
  sourceSnapshotHash: string;
  groups: CanonicalizationGroup[];
}

/**
 * Relationship conflict detected during preflight.
 */
interface RelationshipConflict {
  trainerId: string;
  duplicateUrl: string;
  canonicalUrl: string;
}

/**
 * Page group analysis result from preflight.
 */
interface PageGroupAnalysis {
  groupId: string;
  exerciseName: string;
  canonicalExists: boolean;
  duplicatesCount: number;
  duplicatesMissing: string[];
  relationshipConflicts: RelationshipConflict[];
}

// Cached plan instance
let PLAN: CanonicalizationPlan | null = null;

/**
 * Load the generated canonicalization plan.
 * Imports from canonicalizationPlan.ts which is generated by scripts.
 */
async function loadPlan(): Promise<CanonicalizationPlan> {
  if (PLAN) {
    return PLAN;
  }
  
  // Import the generated plan module
  // Note: This requires canonicalizationPlan.ts to be generated first
  try {
    // Direct import of the generated plan module
    const planModule = await import('./canonicalizationPlan.js');
    PLAN = {
      planVersion: planModule.planVersion || '1.0.0',
      generatedAt: planModule.generatedAt || Date.now(),
      groupsHash: planModule.groupsHash || '',
      sourceSnapshotHash: planModule.sourceSnapshotHash || '',
      groups: planModule.groups || [],
    };
    return PLAN;
  } catch (error) {
    throw new Error(`Failed to load canonicalization plan: ${error}. Please run 'cd scripts/canonicalization && npm run generate' first.`);
  }
}

// ============== Helper Functions ==============

/**
 * Get migration state - inline helper
 */
async function getMigrationState(ctx: QueryCtx | MutationCtx) {
  const states = await ctx.db
    .query('migrationState')
    .withIndex('by_name_status', (q) => q.eq('migrationName', 'canonicalizeExercises'))
    .collect();
  
  if (states.length === 0) {
    return null;
  }
  
  if (states.length > 1) {
    throw new Error(
      `Multiple migration state rows found for canonicalizeExercises: ${states.length}`
    );
  }
  
  return states[0];
}

/**
 * Merge two trainerExercise relationships with complete field-by-field comparison.
 * Returns patch data and whether merge was blocked.
 */
async function mergeTrainerExerciseRelationships(
  canonical: Doc<'trainerExercises'>,
  duplicate: Doc<'trainerExercises'>,
  ctx: MutationCtx
): Promise<{ blocked: boolean; patch: Partial<Doc<'trainerExercises'>> }> {
  const patch: Partial<Doc<'trainerExercises'>> = {};
  let blocked = false;
  
  // videoUrl: Compare normalized hashes, block if both valid and different
  const normalizeUrl = (url: string) => url.trim().toLowerCase();
  const canonicalUrl = canonical.videoUrl ? normalizeUrl(canonical.videoUrl) : '';
  const duplicateUrl = duplicate.videoUrl ? normalizeUrl(duplicate.videoUrl) : '';
  
  if (canonicalUrl && duplicateUrl && canonicalUrl !== duplicateUrl) {
    blocked = true;
  } else if (duplicateUrl && !canonicalUrl) {
    patch.videoUrl = duplicate.videoUrl;
  }
  
  // isActive: true wins
  if (duplicate.isActive && !canonical.isActive) {
    patch.isActive = true;
  }
  
  // notionPageId: Equal → keep; Different → block
  if (canonical.notionPageId && duplicate.notionPageId && canonical.notionPageId !== duplicate.notionPageId) {
    blocked = true;
  } else if (duplicate.notionPageId && !canonical.notionPageId) {
    patch.notionPageId = duplicate.notionPageId;
  }
  
  // sourceType: Prefer non-empty; block if different and both non-empty
  if (canonical.sourceType && duplicate.sourceType && canonical.sourceType !== duplicate.sourceType) {
    blocked = true;
  } else if (duplicate.sourceType && !canonical.sourceType) {
    patch.sourceType = duplicate.sourceType;
  }
  
  // assignedAt: Keep earlier timestamp
  if (duplicate.assignedAt && (!canonical.assignedAt || duplicate.assignedAt < canonical.assignedAt)) {
    patch.assignedAt = duplicate.assignedAt;
  }
  
  // updatedAt: Keep later timestamp
  if (duplicate.updatedAt && (!canonical.updatedAt || duplicate.updatedAt > canonical.updatedAt)) {
    patch.updatedAt = duplicate.updatedAt;
  }
  
  return { blocked, patch };
}

/**
 * Build a patch object from CanonicalPatch structure.
 * Only includes fields that have a non-null 'to' value.
 */
function buildCanonicalPatch(patch: CanonicalPatch): Partial<Doc<'exercises'>> {
  const result: Partial<Doc<'exercises'>> = {};
  
  if (patch.overview?.to !== undefined && patch.overview?.to !== null) {
    result.overview = patch.overview.to;
  }
  
  if (patch.benefits?.to !== undefined && patch.benefits?.to !== null) {
    result.benefits = patch.benefits.to;
  }
  
  if (patch.primaryMuscles?.to !== undefined && patch.primaryMuscles?.to !== null) {
    result.primaryMuscles = patch.primaryMuscles.to;
  }
  
  if (patch.secondaryMuscles?.to !== undefined && patch.secondaryMuscles?.to !== null) {
    result.secondaryMuscles = patch.secondaryMuscles.to;
  }
  
  if (patch.equipment?.to !== undefined && patch.equipment?.to !== null) {
    result.equipment = patch.equipment.to;
  }
  
  if (patch.tags?.to !== undefined && patch.tags?.to !== null) {
    result.tags = patch.tags.to;
  }
  
  if (patch.instructions?.to !== undefined && patch.instructions?.to !== null) {
    result.instructions = patch.instructions.to;
  }
  
  if (patch.sets?.to !== undefined && patch.sets?.to !== null) {
    result.sets = patch.sets.to;
  }
  
  if (patch.reps?.to !== undefined && patch.reps?.to !== null) {
    result.reps = patch.reps.to;
  }
  
  if (patch.tempo?.to !== undefined && patch.tempo?.to !== null) {
    result.tempo = patch.tempo.to;
  }
  
  if (patch.rest?.to !== undefined && patch.rest?.to !== null) {
    result.rest = patch.rest.to;
  }
  
  if (patch.weight?.to !== undefined && patch.weight?.to !== null) {
    result.weight = patch.weight.to;
  }
  
  return result;
}

// ============== Public Functions (require admin secret) ==============

/**
 * Get migration state (public, with auth check).
 */
export const getCanonicalizationState = query({
  args: requireAdminSecret,
  handler: async (ctx, args) => {
    assertAdminSecret(args.adminSecret);
    
    const states = await ctx.db
      .query('migrationState')
      .withIndex('by_name_status', (q) => q.eq('migrationName', 'canonicalizeExercises'))
      .collect();
    
    if (states.length === 0) {
      return null;
    }
    
    if (states.length > 1) {
      throw new Error(
        `Multiple migration state rows found for canonicalizeExercises: ${states.length}`
      );
    }
    
    return states[0];
  },
});

/**
 * Run complete preflight checks.
 * PUBLIC QUERY - requires admin secret.
 */
export const runPreflight = query({
  args: requireAdminSecret,
  handler: async (ctx, args) => {
    assertAdminSecret(args.adminSecret);
    
    const plan = await loadPlan();
    const pageSize = 10;
    
    // Run init checks
    // Verify plan hash matches
    if (plan.groupsHash !== plan.groupsHash) {
      throw new Error('Plan hash mismatch');
    }
    
    // Check current exercise count
    const allExercises = await ctx.db.query('exercises').collect();
    const currentCount = allExercises.length;
    const expectedAfter = currentCount - plan.groups.reduce(
      (sum, g) => sum + g.duplicateExerciseIds.length,
      0
    );
    
    // Check for missing canonical exercises
    const missingCanonical: string[] = [];
    for (const group of plan.groups) {
      const exists = await ctx.db.get(group.canonicalExerciseId as Id<'exercises'>);
      if (!exists) {
        missingCanonical.push(group.canonicalExerciseId);
      }
    }
    
    // Check for missing duplicate exercises
    const missingDuplicates: string[] = [];
    for (const group of plan.groups) {
      for (const dupId of group.duplicateExerciseIds) {
        const exists = await ctx.db.get(dupId as Id<'exercises'>);
        if (!exists) {
          missingDuplicates.push(dupId);
        }
      }
    }
    
    const initResult = {
      valid: missingCanonical.length === 0 && missingDuplicates.length === 0,
      currentExerciseCount: currentCount,
      expectedAfter,
      totalGroups: plan.groups.length,
      totalDuplicatesToRemove: plan.groups.reduce(
        (sum, g) => sum + g.duplicateExerciseIds.length,
        0
      ),
      missingCanonical,
      missingDuplicates,
    };
    
    if (!initResult.valid) {
      return {
        status: 'failed',
        init: initResult,
        pages: [],
        summary: {
          totalGroups: plan.groups.length,
          totalPages: 0,
          analyzedGroups: 0,
          conflictsFound: 0,
          missingExercises:
            initResult.missingCanonical.length + initResult.missingDuplicates.length,
        },
      };
    }
    
    // Analyze pages
    const pages = [];
    const totalPages = Math.ceil(plan.groups.length / pageSize);
    let conflictsFound = 0;
    
    for (let offset = 0; offset < plan.groups.length; offset += pageSize) {
      // Verify plan hash
      if (plan.groupsHash !== plan.groupsHash) {
        throw new Error('Plan hash mismatch during page analysis');
      }

      // Get the slice of groups
      const groupsSlice = plan.groups.slice(offset, offset + pageSize);

      const pageGroups: PageGroupAnalysis[] = [];

      for (const group of groupsSlice) {
        const canonical = await ctx.db.get(group.canonicalExerciseId as Id<'exercises'>);

        // Check duplicates
        const duplicatesMissing: string[] = [];
        const relationshipConflicts: RelationshipConflict[] = [];

        for (const dupId of group.duplicateExerciseIds) {
          const duplicate = await ctx.db.get(dupId as Id<'exercises'>);
          if (!duplicate) {
            duplicatesMissing.push(dupId);
            continue;
          }

          // Check trainerExercises for conflicts
          const trainerExercises = await ctx.db
            .query('trainerExercises')
            .withIndex('by_exercise', (q) => q.eq('exerciseId', dupId as Id<'exercises'>))
            .collect();

          for (const te of trainerExercises) {
            // Check if canonical also has a relationship with this trainer
            const canonicalTe = await ctx.db
              .query('trainerExercises')
              .withIndex('by_trainer_exercise', (q) =>
                q.eq('trainerId', te.trainerId).eq('exerciseId', group.canonicalExerciseId as Id<'exercises'>)
              )
              .first();
            
            if (canonicalTe && te.videoUrl && canonicalTe.videoUrl) {
              // Normalize URLs for comparison
              const dupUrl = te.videoUrl.trim().toLowerCase();
              const canUrl = canonicalTe.videoUrl.trim().toLowerCase();
              
              if (dupUrl !== canUrl) {
                relationshipConflicts.push({
                  trainerId: te.trainerId as string,
                  duplicateUrl: te.videoUrl,
                  canonicalUrl: canonicalTe.videoUrl,
                });
                conflictsFound++;
              }
            }
          }
        }
        
        pageGroups.push({
          groupId: group.groupId,
          exerciseName: group.exerciseName,
          canonicalExists: !!canonical,
          duplicatesCount: group.duplicateExerciseIds.length,
          duplicatesMissing,
          relationshipConflicts,
        });
      }
      
      pages.push({
        offset,
        limit: pageSize,
        totalGroups: plan.groups.length,
        analyzedGroups: pageGroups.length,
        groups: pageGroups,
      });
    }
    
    return {
      status: 'success',
      init: initResult,
      pages,
      summary: {
        totalGroups: plan.groups.length,
        totalPages,
        analyzedGroups: plan.groups.length,
        conflictsFound,
        missingExercises: 0,
      },
    };
  },
});

/**
 * Initialize canonicalization migration.
 * PUBLIC MUTATION - requires admin secret.
 */
export const canonicalizeExercises_initialize = mutation({
  args: v.object({
    adminSecret: v.optional(v.string()),
    operatorId: v.optional(v.string()),
  }),
  handler: async (ctx, args) => {
    assertAdminSecret(args.adminSecret);
    
    const plan = await loadPlan();
    const operatorId = args.operatorId || 'unknown';
    const now = Date.now();
    
    // Check for existing state
    const existing = await getMigrationState(ctx);
    
    if (existing) {
      // Preserve existing state for lock takeover
      return {
        stateId: existing._id,
        status: existing.status,
        lockToken: existing.lockToken,
        totalGroups: plan.groups.length,
      };
    }
    
    // Create new state
    const lockToken = await generateLockToken();
    const stateId = await ctx.db.insert('migrationState', {
      migrationName: 'canonicalizeExercises',
      planHash: plan.groupsHash,
      status: 'pending',
      startedAt: now,
      updatedAt: now,
      completedAt: undefined,
      totalGroups: plan.groups.length,
      completedGroupIds: [],
      completedBatchIds: [],
      blockedGroupIds: undefined,
      lockToken,
      lockOwnerId: operatorId,
      lockAcquiredAt: now,
      lockExpiresAt: now + 30 * 60 * 1000, // 30 minutes
      operatorId: operatorId,
      preflightHash: undefined,
      batchManifest: undefined,
      totalBatches: 0,
      currentBatchId: undefined,
      failureReason: undefined,
      errorDetails: undefined,
    });
    
    logMigration(`Migration state initialized: ${stateId}`);
    
    // Return lock token to operator (don't log it)
    return {
      stateId,
      status: 'pending',
      lockToken,
      totalGroups: plan.groups.length,
    };
  },
});

/**
 * Run complete preflight and finalize.
 * PUBLIC MUTATION - requires admin secret.
 */
export const canonicalizeExercises_preflight = mutation({
  args: v.object({
    adminSecret: v.optional(v.string()),
    lockToken: v.string(),
  }),
  handler: async (ctx, args) => {
    assertAdminSecret(args.adminSecret);
    
    // Validate lock token format (don't log it)
    if (!isValidLockToken(args.lockToken)) {
      throw new Error('Invalid lock token format');
    }
    
    // Get state
    const state = await getMigrationState(ctx);
    
    if (!state) {
      throw new Error('Migration state not found');
    }
    
    const now = Date.now();
    const lockTimeout = 30 * 60 * 1000;
    
    // Check for stale lock or validate current lock
    if (state.lockExpiresAt && state.lockExpiresAt < now) {
      // Lock is stale - allow takeover with new token
      const newToken = await generateLockToken();
      await ctx.db.patch(state._id, {
        lockToken: newToken,
        lockOwnerId: 'preflight',
        lockAcquiredAt: now,
        lockExpiresAt: now + lockTimeout,
        updatedAt: now,
      });
      
      logMigration(`Lock takeover by preflight (previous lock expired)`);
      args.lockToken = newToken;
    } else if (state.lockToken !== args.lockToken) {
      throw new Error('Migration is locked by another operator');
    } else {
      // Renew lock
      await ctx.db.patch(state._id, {
        lockExpiresAt: now + lockTimeout,
        updatedAt: now,
      });
    }
    
    const newLockToken = args.lockToken;
    
    // Run preflight analysis inline (to avoid ctx.runQuery issues)
    const plan = await loadPlan();
    const pageSize = 10;
    
    // Run init checks inline
    const allExercises = await ctx.db.query('exercises').collect();
    const currentCount = allExercises.length;
    const expectedAfter = currentCount - plan.groups.reduce(
      (sum, g) => sum + g.duplicateExerciseIds.length,
      0
    );
    
    // Check for missing canonical exercises
    const missingCanonical: string[] = [];
    for (const group of plan.groups) {
      const exists = await ctx.db.get(group.canonicalExerciseId as Id<'exercises'>);
      if (!exists) {
        missingCanonical.push(group.canonicalExerciseId);
      }
    }
    
    // Check for missing duplicate exercises
    const missingDuplicates: string[] = [];
    for (const group of plan.groups) {
      for (const dupId of group.duplicateExerciseIds) {
        const exists = await ctx.db.get(dupId as Id<'exercises'>);
        if (!exists) {
          missingDuplicates.push(dupId);
        }
      }
    }
    
    const initResult = {
      valid: missingCanonical.length === 0 && missingDuplicates.length === 0,
      currentExerciseCount: currentCount,
      expectedAfter,
      totalGroups: plan.groups.length,
      totalDuplicatesToRemove: plan.groups.reduce(
        (sum, g) => sum + g.duplicateExerciseIds.length,
        0
      ),
      missingCanonical,
      missingDuplicates,
    };
    
    if (!initResult.valid) {
      await ctx.db.patch(state._id, {
        lockExpiresAt: now,
        updatedAt: now,
      });
      
      return {
        status: 'failed',
        preflight: {
          status: 'failed',
          init: initResult,
          pages: [],
          summary: {
            totalGroups: plan.groups.length,
            totalPages: 0,
            analyzedGroups: 0,
            conflictsFound: 0,
            missingExercises:
              initResult.missingCanonical.length + initResult.missingDuplicates.length,
          },
        },
        lockToken: newLockToken,
      };
    }
    
    // Analyze pages inline
    const pages = [];
    const totalPages = Math.ceil(plan.groups.length / pageSize);
    let conflictsFound = 0;

    for (let offset = 0; offset < plan.groups.length; offset += pageSize) {
      // Get the slice of groups
      const groupsSlice = plan.groups.slice(offset, offset + pageSize);

      const pageGroups: PageGroupAnalysis[] = [];

      for (const group of groupsSlice) {
        const canonical = await ctx.db.get(group.canonicalExerciseId as Id<'exercises'>);

        // Check duplicates
        const duplicatesMissing: string[] = [];
        const relationshipConflicts: RelationshipConflict[] = [];

        for (const dupId of group.duplicateExerciseIds) {
          const duplicate = await ctx.db.get(dupId as Id<'exercises'>);
          if (!duplicate) {
            duplicatesMissing.push(dupId);
            continue;
          }

          // Check trainerExercises for conflicts
          const trainerExercises = await ctx.db
            .query('trainerExercises')
            .withIndex('by_exercise', (q) => q.eq('exerciseId', dupId as Id<'exercises'>))
            .collect();

          for (const te of trainerExercises) {
            // Check if canonical also has a relationship with this trainer
            const canonicalTe = await ctx.db
              .query('trainerExercises')
              .withIndex('by_trainer_exercise', (q) =>
                q.eq('trainerId', te.trainerId).eq('exerciseId', group.canonicalExerciseId as Id<'exercises'>)
              )
              .first();

            if (canonicalTe && te.videoUrl && canonicalTe.videoUrl) {
              // Normalize URLs for comparison
              const dupUrl = te.videoUrl.trim().toLowerCase();
              const canUrl = canonicalTe.videoUrl.trim().toLowerCase();

              if (dupUrl !== canUrl) {
                relationshipConflicts.push({
                  trainerId: te.trainerId as string,
                  duplicateUrl: te.videoUrl,
                  canonicalUrl: canonicalTe.videoUrl,
                });
                conflictsFound++;
              }
            }
          }
        }

        pageGroups.push({
          groupId: group.groupId,
          exerciseName: group.exerciseName,
          canonicalExists: !!canonical,
          duplicatesCount: group.duplicateExerciseIds.length,
          duplicatesMissing,
          relationshipConflicts,
        });
      }
      
      pages.push({
        offset,
        limit: pageSize,
        totalGroups: plan.groups.length,
        analyzedGroups: pageGroups.length,
        groups: pageGroups,
      });
    }
    
    const preflightResult = {
      status: 'success',
      init: initResult,
      pages,
      summary: {
        totalGroups: plan.groups.length,
        totalPages,
        analyzedGroups: plan.groups.length,
        conflictsFound,
        missingExercises: 0,
      },
    };
    
    // Generate batch manifest
    const batchEstimate = estimateBatchSize(plan.groups.length);
    const batches: CanonicalizationBatch[] = [];
    
    for (let i = 0; i < plan.groups.length; i += batchEstimate.recommendedBatchSize) {
      const groupIds = plan.groups
        .slice(i, i + batchEstimate.recommendedBatchSize)
        .map((g) => g.groupId);
      
      const batchId = `batch-${i}-${i + groupIds.length - 1}`;
      batches.push({
        batchId,
        groupIds,
        estimatedReads: batchEstimate.readsPerBatch,
        estimatedWrites: batchEstimate.writesPerBatch,
      });
    }
    
    const batchManifest: CanonicalizationBatchManifest = {
      manifestVersion: '1.0.0',
      manifestHash: await hashObject(batches),
      planHash: plan.groupsHash,
      preflightHash: await hashObject(preflightResult),
      generatedAt: Date.now(),
      totalBatches: batches.length,
      batches,
    };
    
    // Finalize preflight
    await ctx.db.patch(state._id, {
      status: 'pending',
      updatedAt: now,
      preflightHash: batchManifest.preflightHash,
      batchManifest,
      totalBatches: batchManifest.totalBatches,
      currentBatchId: undefined,
      failureReason: undefined,
      errorDetails: undefined,
    });
    
    logMigration(`Preflight finalized: ${batchManifest.totalBatches} batches ready`);
    
    return {
      status: 'success',
      preflight: preflightResult,
      batchManifest: {
        totalBatches: batchManifest.totalBatches,
        batches: batchManifest.batches.map((b) => ({
          batchId: b.batchId,
          groupIds: b.groupIds,
          estimatedReads: b.estimatedReads,
          estimatedWrites: b.estimatedWrites,
        })),
      },
      lockToken: newLockToken,
    };
  },
});

/**
 * Execute a batch of canonicalization.
 * PUBLIC MUTATION - requires admin secret.
 */
export const canonicalizeExercises_executeBatch = mutation({
  args: v.object({
    adminSecret: v.optional(v.string()),
    batchId: v.string(),
    lockToken: v.string(),
  }),
  handler: async (ctx, args) => {
    assertAdminSecret(args.adminSecret);
    
    // Validate lock token format (don't log it)
    if (!isValidLockToken(args.lockToken)) {
      throw new Error('Invalid lock token format');
    }
    
    // Get state
    const state = await getMigrationState(ctx);
    
    if (!state) {
      throw new Error('Migration state not found');
    }
    
    const now = Date.now();
    const lockTimeout = 30 * 60 * 1000;
    
    // Check for stale lock or validate current lock
    if (state.lockExpiresAt && state.lockExpiresAt < now) {
      // Lock is stale - allow takeover with new token
      const newToken = await generateLockToken();
      await ctx.db.patch(state._id, {
        lockToken: newToken,
        lockOwnerId: 'executor',
        lockAcquiredAt: now,
        lockExpiresAt: now + lockTimeout,
        updatedAt: now,
      });
      
      logMigration(`Lock takeover by executor (previous lock expired)`);
      args.lockToken = newToken;
    } else if (state.lockToken !== args.lockToken) {
      throw new Error('Migration is locked by another operator');
    } else {
      // Renew lock
      await ctx.db.patch(state._id, {
        lockExpiresAt: now + lockTimeout,
        updatedAt: now,
      });
    }
    
    const newLockToken = args.lockToken;
    
    // Validate hashes
    const plan = await loadPlan();
    if (state.planHash !== plan.groupsHash) {
      throw new Error('Plan hash mismatch');
    }
    
    if (!state.preflightHash) {
      throw new Error('Preflight not run');
    }
    
    // Validate status
    if (state.status !== 'pending' && state.status !== 'running') {
      throw new Error(`Cannot execute batch in status: ${state.status}`);
    }
    
    // Get batch manifest
    if (!state.batchManifest || !state.batchManifest.batches) {
      throw new Error('Batch manifest not found');
    }

    const batch = state.batchManifest.batches.find((b: CanonicalizationBatch) => b.batchId === args.batchId);
    if (!batch) {
      throw new Error(`Batch ${args.batchId} not found in manifest`);
    }
    
    // Check if batch already completed
    if (state.completedBatchIds && state.completedBatchIds.includes(args.batchId)) {
      return {
        batchId: args.batchId,
        status: 'already_completed',
        groupsProcessed: 0,
        duplicatesRemoved: 0,
        relationshipsRedirected: 0,
        conflictsBlocked: 0,
        lockToken: newLockToken,
      };
    }
    
    // Load plan
    const groupMap = new Map(plan.groups.map((g) => [g.groupId, g]));
    
    // Execute batch
    let groupsProcessed = 0;
    let duplicatesRemoved = 0;
    let relationshipsRedirected = 0;
    let conflictsBlocked = 0;
    const blockedGroupIds: string[] = [];
    
    for (const groupId of batch.groupIds) {
      const group = groupMap.get(groupId);
      if (!group) {
        logMigration(`Group ${groupId} not found in plan`, 'warn');
        continue;
      }
      
      // Live-state validation: check preconditions before writes
      const canonical = await ctx.db.get(group.canonicalExerciseId as Id<'exercises'>);
      if (!canonical) {
        logMigration(`Canonical exercise ${group.canonicalExerciseId} not found for group ${groupId}`, 'error');
        blockedGroupIds.push(groupId);
        conflictsBlocked++;
        continue;
      }
      
      // Process duplicates
      for (const duplicateId of group.duplicateExerciseIds) {
        const duplicate = await ctx.db.get(duplicateId as Id<'exercises'>);
        if (!duplicate) {
          logMigration(`Duplicate ${duplicateId} not found (already deleted?)`, 'warn');
          continue;
        }
        
        // Redirect trainerExercises relationships
        const trainerExercises = await ctx.db
          .query('trainerExercises')
          .withIndex('by_exercise', (q) => q.eq('exerciseId', duplicateId as Id<'exercises'>))
          .collect();
        
        for (const te of trainerExercises) {
          // Check for existing relationship to canonical
          const existing = await ctx.db
            .query('trainerExercises')
            .withIndex('by_trainer_exercise', (q) =>
              q.eq('trainerId', te.trainerId).eq('exerciseId', group.canonicalExerciseId as Id<'exercises'>)
            )
            .first();
          
          if (existing) {
            // Merge relationships - complete field-by-field comparison
            const merged = await mergeTrainerExerciseRelationships(existing, te, ctx);
            
            if (merged.blocked) {
              logMigration(
                `Relationship conflict blocked: trainer ${te.trainerId}, exercise ${group.exerciseName}`,
                'warn'
              );
              conflictsBlocked++;
            } else {
              // Update canonical relationship with merged data
              await ctx.db.patch(existing._id, merged.patch);
              relationshipsRedirected++;
              
              // Delete duplicate relationship
              await ctx.db.delete(te._id);
            }
          } else {
            // Redirect relationship to canonical
            await ctx.db.patch(te._id, { exerciseId: group.canonicalExerciseId as Id<'exercises'> });
            relationshipsRedirected++;
          }
        }
        
        // Delete the duplicate exercise
        await ctx.db.delete(duplicateId as Id<'exercises'>);
        duplicatesRemoved++;
      }
      
      // Apply canonical patch if present
      if (group.canonicalPatch) {
        const patch = buildCanonicalPatch(group.canonicalPatch);
        if (Object.keys(patch).length > 0) {
          await ctx.db.patch(canonical._id, patch);
        }
      }
      
      groupsProcessed++;
    }
    
    // Update state
    const completedBatchIds = [...(state.completedBatchIds || []), args.batchId];
    const completedGroupIds = [...(state.completedGroupIds || []), ...batch.groupIds];
    
    await ctx.db.patch(state._id, {
      status: 'running',
      updatedAt: now,
      completedBatchIds,
      completedGroupIds,
      blockedGroupIds: [...(state.blockedGroupIds || []), ...blockedGroupIds].filter(
        (id, i, arr) => arr.indexOf(id) === i
      ),
      currentBatchId: args.batchId,
    });
    
    logMigration(
      `Batch ${args.batchId} completed: ${groupsProcessed} groups, ${duplicatesRemoved} duplicates removed, ${relationshipsRedirected} relationships redirected, ${conflictsBlocked} conflicts blocked`
    );
    
    return {
      batchId: args.batchId,
      status: 'completed',
      groupsProcessed,
      duplicatesRemoved,
      relationshipsRedirected,
      conflictsBlocked,
      lockToken: newLockToken,
    };
  },
});

/**
 * Complete the migration.
 * PUBLIC MUTATION - requires admin secret.
 */
export const canonicalizeExercises_complete = mutation({
  args: v.object({
    adminSecret: v.optional(v.string()),
    lockToken: v.string(),
  }),
  handler: async (ctx, args) => {
    assertAdminSecret(args.adminSecret);
    
    // Validate lock token format (don't log it)
    if (!isValidLockToken(args.lockToken)) {
      throw new Error('Invalid lock token format');
    }
    
    // Get state
    const state = await getMigrationState(ctx);
    
    if (!state) {
      throw new Error('Migration state not found');
    }
    
    // Verify lock token
    if (state.lockToken !== args.lockToken) {
      throw new Error('Invalid lock token');
    }
    
    const now = Date.now();
    
    // Verify all batches completed
    if (!state.batchManifest || state.completedBatchIds.length !== state.batchManifest.totalBatches) {
      throw new Error(
        `Not all batches completed: ${state.completedBatchIds.length}/${state.batchManifest?.totalBatches}`
      );
    }
    
    // Mark as completed
    await ctx.db.patch(state._id, {
      status: 'completed',
      updatedAt: now,
      completedAt: now,
      lockExpiresAt: now, // Release lock
    });
    
    logMigration('Migration completed successfully');
    
    // Verify final state
    const allExercises = await ctx.db.query('exercises').collect();
    const plan = await loadPlan();
    const expectedCount = 1100 - plan.groups.reduce((sum, g) => sum + g.duplicateExerciseIds.length, 0);
    
    return {
      status: 'completed',
      finalExerciseCount: allExercises.length,
      expectedCount,
      groupsProcessed: state.completedGroupIds.length,
      batchesCompleted: state.completedBatchIds.length,
      blockedGroups: state.blockedGroupIds || [],
    };
  },
});

/**
 * Pause the migration.
 * PUBLIC MUTATION - requires admin secret.
 */
export const canonicalizeExercises_pause = mutation({
  args: v.object({
    adminSecret: v.optional(v.string()),
    lockToken: v.string(),
  }),
  handler: async (ctx, args) => {
    assertAdminSecret(args.adminSecret);
    
    // Get state
    const state = await getMigrationState(ctx);
    
    if (!state) {
      throw new Error('Migration state not found');
    }
    
    // Verify lock token
    if (state.lockToken !== args.lockToken) {
      throw new Error('Invalid lock token');
    }
    
    const now = Date.now();
    
    // Mark as paused
    await ctx.db.patch(state._id, {
      status: 'paused',
      updatedAt: now,
      lockExpiresAt: now, // Release lock
    });
    
    logMigration('Migration paused');
    
    return {
      status: 'paused',
      batchesCompleted: state.completedBatchIds.length,
      groupsProcessed: state.completedGroupIds.length,
    };
  },
});

/**
 * Verify canonicalization results.
 * PUBLIC QUERY - requires admin secret.
 */
export const verifyCanonicalization = query({
  args: requireAdminSecret,
  handler: async (ctx, args) => {
    assertAdminSecret(args.adminSecret);
    
    const allExercises = await ctx.db.query('exercises').collect();
    
    // Check for duplicates by name
    const nameMap = new Map<string, Doc<'exercises'>[]>();
    for (const ex of allExercises) {
      const normName = ex.name.toLowerCase().trim();
      if (!nameMap.has(normName)) {
        nameMap.set(normName, []);
      }
      nameMap.get(normName)!.push(ex);
    }
    
    const duplicates = Array.from(nameMap.entries())
      .filter(([_, exs]) => exs.length > 1)
      .map(([name, exs]) => ({ name, count: exs.length, ids: exs.map((e) => e._id) }));
    
    return {
      totalExercises: allExercises.length,
      expectedCount: 938,
      duplicatesFound: duplicates.length,
      duplicateGroups: duplicates,
      isCanonicalized: duplicates.length === 0 && allExercises.length === 938,
    };
  },
});